### ISSUE TITLE
couldn't login

### ISSUE THREAD

**Issue by amenihaouel** [Rainbow-CPaaS/Rainbow-Android-SDK-Sample-AudioAndVideoCallsUsingWebRTC#1]
I have a sandbox Login and password but i couldn't access the app!
How can I resolve this problem?

**Comment by jon67400** [comment]
Hello,

as said in the readme, could you check this please?

Remember :

"If you have this error (Unknown application or wrong token for application id YOUR APPLICATION IDENTIFIER) when you attempt to login, please enter your own application id and application secret or try to remove default values in MyApp class.

To know how can you have an application id and an application secret, please refer to [hub.openrainbow.com]."

**Comment by amenihaouel** [comment]
but i couldn't find how to create an application to get the app Id and the secret Key!
I think it's not available yet!:
https://support.openrainbow.com/hc/en-us/community/posts/360000099684-Unable-to-Create-Application

**Comment by jon67400** [comment]
i, MyApp.jav cgange this line " RainbowSdk.instance().initialize(applicationId, applicationSecret);" by " RainbowSdk.instance().initialize();" and normally, it will be ok

**Comment by amenihaouel** [comment]
it works! Thank you!
